### ISSUE TITLE
Update Forge to newer versions

### ISSUE THREAD

**Issue by OoLunar** [flowerinsnowdh/GreatScrollableTooltips#44]
Hello!

I'm looking to use this mod for my custom modpack, however there is no version available for Forge 1.19.2. I see that right now you have some versions for Forge already (1.8.9, 1.10, 1.11, 1.12). Would you be willing to update to the newer version as well?

Thank you!

**Comment by flowerinsnowdh** [comment]
您好！之所以这个 Mod 没有 Forge 1.13+ 版本，是因为我本不打算开发新版本 Forge 的 Mod，因为它们的变化太大了，让我有些摸不着头脑。

不过既然有需要，那我会去尝试的，但可能不会适配所有版本。

您是想要 1.19.2-forge 版本嘛，请给我一些时间让我研究一下它们。

如果您有别的需求，请继续回复我。

非常感谢您将我的 Mod 加入您的自定义模组包，这是我最大的荣幸！但是我必须提醒您，之前已经发生过类似的不兼容的情况了，这个 Mod 更适合原版而不是模组包，有许多 Mod 可能与它冲突，请将对兼容度的期望值降低。

<hr />

Hello! The reason why this mod does not have a Forge 1.13+ version is because I didn't plan to develop mods for newer versions of Forge, because the changes of different versions of Forge are too big and I am a little confused.

But since there is a need, I will try it, but I may not to make it for all versions.

Did you want the 1.19.2-forge version? Please give me some time to research them.

If you have other needs, please continue to reply me.

Thank you so much for adding my mod to your custom modpack, it's my greatest pleasure! But I must remind you that similar incompatibilities have occurred before. This Mod is more suitable for the vanilla version rather than the modpack. There are many Mods that may conflict with it. Please lower your expectations for compatibility.

**Comment by OoLunar** [comment]
> Did you want the 1.19.2-forge version? Please give me some time to research them.

Yes, just 1.19.2. I *might*  update my modpack to 1.20, but I'm still unsure about it. If you could focus on 1.19.2, I would really appreciate it. Don't worry about 1.20 unless if it's an easy task.

> Thank you so much for adding my mod to your custom modpack, it's my greatest pleasure! But I must remind you that similar incompatibilities have occurred before. This Mod is more suitable for the vanilla version rather than the modpack. There are many Mods that may conflict with it. Please lower your expectations for compatibility.

That's okay! I just want to be able to read my tooltips. It's okay if I can't read all of it, I just want to be able to read a little more than what I have right now.

Thank you for replying and putting in the effort! It means a lot to me. If there's anything I can do to help, please don't be afraid to reach out.

---

> 您是想要 1.19.2-forge 版本嘛，请给我一些时间让我研究一下它们。

是的，只有 1.19.2。 我*可能*将我的 modpack 更新到 1.20，但我仍然不确定。 如果您能关注 1.19.2，我将非常感激。 不要担心 1.20，除非这是一个简单的任务。

> 非常感谢您将我的 Mod 加入您的自定义模组包，这是我最大的荣幸！但是我必须提醒您，之前已经发生过类似的不兼容的情况了，这个 Mod 更适合原版而不是模组包，有许多 Mod 可能与它冲突，请将对兼容度的期望值降低。

没关系！ 我只想能够阅读我的工具提示。 如果我不能读完所有内容也没关系，我只想比现在多读一点。

感谢您的回复和付出的努力！ 它对我意义重大。 如果有什么我可以帮忙的，请不要害怕与我联系。

---

![2024-05-17_16 17 01](https://github.com/flowerinsnow-lights-opensource/GreatScrollableTooltips/assets/46751150/4ec26f4d-5432-419c-ae46-a48f8dd68f4b)
![2024-05-17_16 16 56](https://github.com/flowerinsnow-lights-opensource/GreatScrollableTooltips/assets/46751150/d7bbf5e0-5a91-43b2-ae93-e0f503e617e0)
![2024-05-17_16 17 07](https://github.com/flowerinsnow-lights-opensource/GreatScrollableTooltips/assets/46751150/760126fe-84aa-4f9a-b32c-c312131b9bbf)

**Comment by flowerinsnowdh** [comment]
好了，您可以尝试一下。

https://github.com/flowerinsnow-lights-opensource/GreatScrollableTooltips/releases/tag/v11.0.0-beta.1%2Bforge

or modrinth/curseforge

我暂时只支持了这一个版本，其他版本或许以后吧。

如果您需要更多版本的支持，请再次与我联系，感谢您的支持！

<hr />

It's done, you can try it.

https://github.com/flowerinsnow-lights-opensource/GreatScrollableTooltips/releases/tag/v11.0.0-beta.1%2Bforge

or modrinth/curseforge

I only made for this version for now, Maybe more versions will be supported later.

If you need support for more versions, please contact me again. Thank you for your support!

**Comment by OoLunar** [comment]
It works perfectly! Thank you so much!
