### ISSUE TITLE
1.19.2forge的配置文件有问题

### ISSUE THREAD

**Issue by sjzd123456** [flowerinsnowdh/GreatScrollableTooltips#63]
无法在模组菜单中打开配置文件，并且 在点击“设置”按钮时会崩溃退出游戏。
可能是因为配置文件的后缀是conf？毕竟大多数配置文件都是toml后缀的。

**Comment by flowerinsnowdh** [comment]
您好！感谢您的反馈。

经过我的测试，于1.19.2-forge上的11.0.0-beta.1+forge版本没有出现游戏崩溃的问题。

我正在使用的配置文件不是 TOML 格式，所以没有使用 .toml 后缀，此问题应该与此无关。

请您提供更多信息，例如游戏崩溃日志、Mod版本、Forge版本、已装Mod列表等等，非常感谢！

**Comment by flowerinsnowdh** [comment]
Fixed with commit https://github.com/flowerinsnow-lights-opensource/GreatScrollableTooltips/commit/a6efa57ef3de3002f6a891c6e905708fb0eb3e3c

The reason for this problem is that the old version of forge misses an invoked method, while the new version has it. And this mod is developed based on the new version.
